# Generated by Django 4.0.1 on 2022-02-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('institute_fnid', 'code')},
        ),
    ]
