# Generated by Django 4.0.1 on 2022-02-10 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_fnid', models.CharField(max_length=128)),
                ('student_fnid', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('course_fnid', 'student_fnid')},
            },
        ),
    ]
