# Generated by Django 4.0.1 on 2022-02-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='course_fnid',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student_fnid',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
