# Generated by Django 4.0.1 on 2022-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursestudent_course_fnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute_fnid',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
