# Generated by Django 4.0.1 on 2022-02-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_institute_fnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='course_fnid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='student_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
