# Generated by Django 4.0.1 on 2022-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_coursestudent_course_fnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='institute_fnid',
            field=models.CharField(default='7d22433f-8e41-416f-be47-8d28f81b5195', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='institute_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
