# Generated by Django 4.0.1 on 2022-04-05 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_weeks',
            field=models.IntegerField(default=52, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='course',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_week',
            field=models.IntegerField(default=36, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='threshold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
