# Generated by Django 4.0.1 on 2022-05-19 09:11

import datetime
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_courseintake_coursestudent_intake_fnid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInstance',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('course_fnid', models.CharField(max_length=128)),
                ('start', models.DateField(default=datetime.datetime(2022, 5, 19, 10, 11, 39, 57743))),
                ('duration_weeks', models.IntegerField(default=52, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CourseIntake',
        ),
    ]
