# Generated by Django 4.0.1 on 2022-05-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_courseinstance_delete_courseintake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
