# Generated by Django 4.0.1 on 2022-05-19 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_courseinstance_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='repeat',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='threshold',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='repeat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='threshold',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
