# Generated by Django 4.0.1 on 2022-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_intake_fnid_coursestudent_course_instance_fnid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='term_fnid',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
