# Generated by Django 4.0.1 on 2022-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_courseinstance_duration_weeks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinstance',
            old_name='end',
            new_name='end_date_override',
        ),
        migrations.RenameField(
            model_name='courseinstance',
            old_name='start',
            new_name='registration_start_override',
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='start_date_override',
            field=models.DateField(blank=True, null=True),
        ),
    ]
