# Generated by Django 4.0.1 on 2022-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_rename_end_courseinstance_end_date_override_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstance',
            options={},
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='name_override',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstance',
            unique_together={('term_fnid', 'name_override')},
        ),
    ]
