# Generated by Django 4.0.1 on 2022-09-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_courseinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('institute_fnid', 'course_instance_fnid', 'student_fnid')},
        ),
        migrations.RemoveField(
            model_name='coursestudent',
            name='course_fnid',
        ),
    ]
