# Generated by Django 4.0.1 on 2022-09-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_coursestudent_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseStudent',
            new_name='CourseInstanceStudent',
        ),
    ]
