# Generated by Django 4.0.1 on 2022-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_rename_coursestudent_courseinstancestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='last_session',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseinstancestudent',
            name='average_attend_pc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='courseinstancestudent',
            name='resit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='name_override',
            field=models.CharField(default='New course', max_length=128),
        ),
    ]
