# Generated by Django 4.0.1 on 2022-11-26 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_courseinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstance',
            options={},
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='threshold_override',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='courseinstance',
            unique_together={('term_fnid', 'name_override')},
        ),
        migrations.RemoveField(
            model_name='courseinstance',
            name='threshold',
        ),
    ]
