# Generated by Django 3.2.9 on 2023-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_alter_courseinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='course_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='term_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='courseinstancestudent',
            name='course_instance_fnid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseinstancestudent',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='courseinstancestudent',
            name='student_fnid',
            field=models.UUIDField(),
        ),
    ]
