# Generated by Django 3.2.9 on 2023-07-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20230708_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
