# Generated by Django 3.2.9 on 2023-07-18 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_courseinstance_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.UUIDField()),
                ('group_fnid', models.UUIDField()),
                ('student_fnid', models.UUIDField()),
            ],
            options={
                'unique_together': {('group_fnid', 'student_fnid')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.UUIDField()),
                ('course_instance_fnid', models.UUIDField()),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('course_instance_fnid', 'name')},
            },
        ),
    ]
