# Generated by Django 3.2.9 on 2023-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_group_groupstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='term_fnid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
