# Generated by Django 3.2.9 on 2023-07-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_alter_courseinstance_term_fnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='(e.g. MATH101)', max_length=20),
        ),
    ]
