# Generated by Django 4.0.1 on 2022-02-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='institute_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
