# Generated by Django 4.0.1 on 2022-02-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_institute_fnid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('institute_fnid', 'name')},
        ),
    ]
