# Generated by Django 3.2.9 on 2023-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_institute_fnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
    ]
