# Generated by Django 4.0.1 on 2022-02-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('school_fnid', 'name')},
        ),
    ]
