# Generated by Django 4.0.1 on 2022-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_alter_programme_institute_fnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='institute_fnid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='programme',
            name='school_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
