# Generated by Django 4.0.1 on 2022-05-18 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_alter_programme_institute_fnid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='term_start_date_override',
            field=models.PositiveIntegerField(default=34, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
