# Generated by Django 4.0.1 on 2023-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_rename_term_start_week_override_programme_term_start_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='code',
            field=models.CharField(blank=None, max_length=9, null=True),
        ),
    ]
