# Generated by Django 3.2.9 on 2023-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_auto_20230708_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
