# Generated by Django 4.0.1 on 2022-02-06 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('school_fnid', models.CharField(blank=True, max_length=128, null=True)),
                ('programme_fnid', models.CharField(blank=True, max_length=128, null=True)),
                ('year_of_study', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True)),
                ('student_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('international', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('institute_fnid', 'student_id')},
            },
        ),
    ]
