# Generated by Django 4.0.1 on 2022-02-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_school_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='treharne@liverpool.ac.uk', max_length=128),
            preserve_default=False,
        ),
    ]
