# Generated by Django 4.0.1 on 2022-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_school_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Student',
        ),
    ]
