# Generated by Django 4.0.1 on 2022-02-07 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEmail',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_fnid', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
