# Generated by Django 4.0.1 on 2022-02-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentemail_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentemail',
            name='institute_fnid',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentemail',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
