# Generated by Django 4.0.1 on 2022-05-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_year_of_study_student_year_fnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year_fnid',
        ),
    ]
