# Generated by Django 4.0.1 on 2022-05-24 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_year_of_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTerm',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('student_fnid', models.CharField(max_length=128)),
                ('term_fnid', models.CharField(max_length=128)),
                ('current', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
