# Generated by Django 4.0.1 on 2022-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_studentterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='undergraduate',
            field=models.BooleanField(default=True),
        ),
    ]
