# Generated by Django 4.0.1 on 2022-09-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
