# Generated by Django 4.0.1 on 2022-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_student_id_alter_student_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_attend_pc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
