# Generated by Django 4.0.1 on 2023-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_student_average_attend_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_attend_pc',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
