# Generated by Django 3.2.9 on 2023-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme_fnid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_fnid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentemail',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='studentemail',
            name='student_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='student_fnid',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='studentterm',
            name='term_fnid',
            field=models.UUIDField(),
        ),
    ]
