# Generated by Django 4.0.1 on 2022-02-04 10:23

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('institute_fnid', models.CharField(default='7d22433f-8e41-416f-be47-8d28f81b5195', max_length=128)),
                ('domain', models.CharField(max_length=128, validators=[django.core.validators.URLValidator])),
                ('primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='institute',
            name='id',
        ),
        migrations.AlterField(
            model_name='institute',
            name='fnid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
