# Generated by Django 4.0.1 on 2022-02-01 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='fnid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
