# Generated by Django 4.0.1 on 2022-02-01 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_remove_institute_fnid_institute_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='id',
        ),
        migrations.AddField(
            model_name='institute',
            name='fnid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
