# Generated by Django 4.0.1 on 2022-02-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_alter_institutedomain_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedomain',
            name='institute_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
