# Generated by Django 4.0.1 on 2022-02-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_alter_institutedomain_institute_fnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
