# Generated by Django 4.0.1 on 2022-02-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_alter_institute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128, unique=True)),
                ('student_id_required', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
