# Generated by Django 4.0.1 on 2022-02-07 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_instituteconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instituteconfig',
            name='id',
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='fnid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
