# Generated by Django 4.0.1 on 2022-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_remove_instituteconfig_id_instituteconfig_fnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteconfig',
            name='institute_fnid',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='institutedomain',
            name='institute_fnid',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
