# Generated by Django 4.0.1 on 2022-02-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_alter_instituteconfig_institute_fnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteconfig',
            name='institute_fnid',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='institutedomain',
            name='institute_fnid',
            field=models.CharField(max_length=128),
        ),
    ]
