# Generated by Django 4.0.1 on 2022-02-23 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_alter_instituteconfig_institute_fnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedomain',
            name='domain',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
