# Generated by Django 4.0.1 on 2022-05-24 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('institute_fnid', 'label')},
            },
        ),
    ]
