# Generated by Django 4.0.1 on 2023-05-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0015_sessiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
