# Generated by Django 4.0.1 on 2023-06-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0017_alter_term_registration_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
