# Generated by Django 3.2.9 on 2023-07-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0019_auto_20230708_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='current',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
