# Generated by Django 3.2.9 on 2023-08-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0020_auto_20230730_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutedomain',
            name='admin_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutedomain',
            name='tenant',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
