# Generated by Django 4.0.1 on 2022-03-04 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('school_fnid', models.CharField(max_length=128)),
                ('course_fnid', models.CharField(max_length=128)),
                ('session_fnid', models.CharField(max_length=128)),
                ('student_fnid', models.CharField(max_length=128)),
                ('session_type_fnid', models.CharField(max_length=128)),
                ('group_fnid', models.CharField(blank=True, default=None, max_length=128)),
                ('verified', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('session_code', models.CharField(blank=True, default=None, max_length=128)),
                ('student_code', models.CharField(max_length=128)),
                ('peer_code', models.CharField(blank=True, default=None, max_length=128)),
                ('peer_verified', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type_fnid', models.CharField(max_length=128)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('school_fnid', models.CharField(max_length=128)),
                ('course_fnid', models.CharField(max_length=128)),
                ('average_attendance', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('session_code', models.CharField(max_length=128)),
                ('duration_hrs', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('session_verification_required', models.BooleanField(default=False)),
                ('peer_verification_required', models.BooleanField(default=False)),
                ('late_hrs', models.DecimalField(decimal_places=1, default=12.0, max_digits=3)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default=None, max_length=256)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
