# Generated by Django 4.0.1 on 2022-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontype',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
