# Generated by Django 4.0.1 on 2022-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_sessiontype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='group_fnid',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='peer_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_code',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
