# Generated by Django 4.0.1 on 2022-03-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_group_fnid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='school_fnid',
        ),
    ]
