# Generated by Django 4.0.1 on 2022-03-16 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_session_school_fnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 11, 44, 19, 59345, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
