# Generated by Django 4.0.1 on 2022-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_session_session_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
