# Generated by Django 4.0.1 on 2022-04-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_session_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='average_attendance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
