# Generated by Django 4.0.1 on 2022-11-26 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_session_average_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('fnid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute_fnid', models.CharField(max_length=128)),
                ('student_fnid', models.CharField(max_length=128)),
                ('course_instance_fnid', models.CharField(max_length=128)),
                ('session_start', models.DateTimeField()),
                ('session_type_fnid', models.CharField(max_length=128)),
                ('duration_hrs', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='SessionType',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='average_attendance',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='course_fnid',
            new_name='course_instance_fnid',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='confirmed',
            new_name='ignore',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='peer_verification_required',
            new_name='session_audit',
        ),
        migrations.RemoveField(
            model_name='session',
            name='late_hrs',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_verification_required',
        ),
    ]
