# Generated by Django 4.0.1 on 2022-11-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_sessionrequest_delete_code_delete_sessiontype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='course_fnid',
            new_name='course_instance_fnid',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='online',
        ),
        migrations.AddField(
            model_name='session',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
