# Generated by Django 4.0.1 on 2022-11-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_rename_course_fnid_attendance_course_instance_fnid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='peer_code',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='peer_verified',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_code',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_code',
        ),
    ]
