# Generated by Django 4.0.1 on 2022-12-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remove_session_duration_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='session_fnid',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
