# Generated by Django 4.0.1 on 2022-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_session_expired_session_session_fnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
