# Generated by Django 4.0.1 on 2022-12-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_sessionrequest_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_fnid',
        ),
    ]
