# Generated by Django 4.0.1 on 2023-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_session_session_fnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='verified_by_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='verified_by_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='void',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled_by',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='void',
            field=models.BooleanField(default=False),
        ),
    ]
