# Generated by Django 4.0.1 on 2023-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendance_verified_by_administrator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='verified_by_administrator',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='verified_by_audit',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
