# Generated by Django 4.0.1 on 2023-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_attendance_verified_by_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='programme_fnid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
