# Generated by Django 3.2.9 on 2023-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_attendance_programme_fnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approved_absence',
            field=models.BooleanField(default=False),
        ),
    ]
