# Generated by Django 3.2.9 on 2023-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendance_approved_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='institute_fnid',
            field=models.UUIDField(),
        ),
    ]
